Updating Readme
Lambda-School-Labs/xcel-wom-be-c pull request #3
Opened 2020-12-15 02:20 UTC by luanvu1711

2020-12-15 02:23 UTC, MrT3313 requested changes

2020-12-15 02:23 UTC, MrT3313 commented on README.md
> +|                                                      [LV](https://github.com/luanvu1711)                                                       |
Hey @luanvu1711 could you add your full name here please?

2020-12-16 00:03 UTC, MrT3313 commented
is this a duplicate?

2021-01-27 01:52 UTC, germainep commented
This pull request is no longer needed so I'm closing it at this time.

2021-01-27 01:52 UTC, closed without merging